language: python
python:
  - "3.8"
env:
  global:
  - GH_REF=github.com/bwinton/weblog.latte.ca.git
script: bash ./deploy.sh


# sudo apt-get install python3-dev
# sudo apt-get install libxml2-dev libxslt1-dev
